// Componentes do Dashboard
export * from './StatCard'
export { DepartmentRanking } from './DepartmentRanking'
export { BirthdaysSection } from './BirthdaysSection'
export { VacationsSection } from './VacationsSection'
export { AttendanceGoal } from './AttendanceGoal'
export { TopPerformers } from './TopPerformers'
export { LowAttendanceAlert } from './LowAttendanceAlert'
export { QuickStatsSection } from './QuickStatsSection'
export { RecentAttendanceTable } from './RecentAttendanceTable'
export { AdditionalMetrics } from './AdditionalMetrics'
export { StatDetailsModal } from './StatDetailsModal'
export { NotificationBanner, GreetingHeader, CelebrationEffect } from './NotificationBanner'
export { default as ImprovementsPopup } from './ImprovementsPopup'
